%
% SP_DSB_CWDM_Simulator_Control_Param_Init;
% SP_DSB_CWDM_Simulator_System_Param_Init;
% SP_SSB_CWDM_Simulator_Control_Param_Init;
% SP_SSB_CWDM_Simulator_System_Param_Init;

deltaOmega = ParamLas.omega0-ParamLas.omega_ref;
estimated_beta2_ignore_beta4 = 2*(1/2*ParamFib.Beta3_ref*deltaOmega);

estimated_beta2 = ParamFib.Beta2_ref+2*(1/2*ParamFib.Beta3_ref*deltaOmega ...
    + 1/4*ParamFib.Beta4_ref*deltaOmega.^2)...
    + 1/12*ParamFib.Beta5_ref*deltaOmega.^3

true_beta2 = ParamFib.Beta2

estimated_beta1 = (ParamFib.Beta1_ref...
    + ParamFib.Beta2_ref*deltaOmega...
    + 1/2*ParamFib.Beta3_ref*deltaOmega.^2 ...
    + 1/6*ParamFib.Beta4_ref*deltaOmega.^3 +...
    + 1/24*ParamFib.Beta5_ref*deltaOmega.^4)


% estimated_beta1 = estimated_beta1-mean(estimated_beta1)

true_beta1 = ParamFib.Beta1

estimated_beta0 = (ParamFib.Beta1_ref*deltaOmega...
    + 1/2*ParamFib.Beta2_ref*deltaOmega.^2 ...
    + 1/6*ParamFib.Beta3_ref*deltaOmega.^3 ...
    + 1/24*ParamFib.Beta4_ref*deltaOmega.^4 ...
    + 1/120*ParamFib.Beta5_ref*deltaOmega.^5);

estimated_beta0 = estimated_beta0-mean(estimated_beta0)...

true_beta0 = ParamFib.Beta0